name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: build and test
        run: |
          go get -v
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" | grep -v "mocks"> $GITHUB_WORKSPACE/profile.cov
          go build -race
        env:
          GO111MODULE: "on"
          TZ: "America/Chicago"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.60.2

      - name: submit coverage
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
